import type { ProjectIdea } from "@/types";

/**
 * Curated, high-quality example projects so the app feels alive and
 * impressive even before an API key is added. Not generated — real seed content.
 */
export const SAMPLE_IDEAS: ProjectIdea[] = [
  {
    id: "sample-1",
    projectName: "Argus — Realtime Voice SRE Copilot",
    description:
      "An on-call copilot that ingests live telemetry, summarizes incidents, and drafts runbooks in natural language.",
    domain: "AI Agents",
    targetUsers: "Platform & DevOps engineers on call",
    problemSolved:
      "Incidents cause alert fatigue and slow triage; engineers drown in dashboards instead of acting.",
    whyPowerful:
      "Combines streaming RAG over logs/metrics with agentic remediation suggestions — a genuine FAANG-grade systems problem.",
    targetCompanies: ["Vercel", "Datadog", "Stripe", "Google"],
    techStack: ["Next.js", "TypeScript", "PostgreSQL", "Gemini API", "LangChain", "Vercel"],
    aiIntegration:
      "Gemini for long-context incident synthesis, Groq for low-latency alert triage, vector store for runbook RAG.",
    databasePlan: "Postgres (incidents, runbooks) + pgvector for embeddings + Redis stream buffer.",
    frontendComplexity: 8,
    backendComplexity: 9,
    deploymentMethod: "Vercel app + containerized ingestion worker on Fly.io",
    scores: {
      resumeImpact: 9.4,
      githubValue: 9.1,
      recruiterImpression: 9.6,
      marketRelevance: 9.3,
      startupPotential: 8.7,
    },
    difficulty: "Industry Level",
    estimatedBuildTime: "4-6 weeks",
    mvpFeatures: [
      "Live incident timeline view",
      "Streaming AI summary of alerts",
      "Runbook search with semantic RAG",
      "Slack/Teams incident bridge",
    ],
    advancedFeatures: [
      "Agentic remediation playbooks",
      "Anomaly clustering across metrics",
      "Postmortem auto-drafting",
    ],
    uiInspiration: ["Linear", "Datadog", "Vercel", "Grafana"],
    monetization: "B2B SaaS per-seat for engineering teams",
  },
  {
    id: "sample-2",
    projectName: "LedgerLens — AI Bookkeeping for Creators",
    description:
      "Auto-categorizes invoices, bank feeds, and platform payouts into tax-ready books for solo creators.",
    domain: "FinTech",
    targetUsers: "Independent creators, freelancers, solopreneurs",
    problemSolved: "Creators juggle many income sources and hate manual bookkeeping.",
    whyPowerful:
      "Real financial data pipeline + LLM classification = sticky fintech product with clear monetization.",
    targetCompanies: ["Stripe", "Mercury", "Notion", "Wave"],
    techStack: ["Next.js", "Supabase", "TypeScript", "Groq API", "PostgreSQL"],
    aiIntegration: "Groq for instant transaction categorization, embeddings for recurring detection.",
    databasePlan: "Supabase Postgres (accounts, transactions, categories) + RLS for multi-tenant.",
    frontendComplexity: 7,
    backendComplexity: 8,
    deploymentMethod: "Vercel + Supabase + Plaid (sandbox)",
    scores: {
      resumeImpact: 8.9,
      githubValue: 8.4,
      recruiterImpression: 9.0,
      marketRelevance: 9.2,
      startupPotential: 9.5,
    },
    difficulty: "Industry Level",
    estimatedBuildTime: "3-5 weeks",
    mvpFeatures: [
      "Bank feed connection (Plaid sandbox)",
      "Auto-categorize transactions",
      "Monthly P&L dashboard",
      "CSV / receipt import",
    ],
    advancedFeatures: [
      "Tax estimate engine",
      "Multi-currency + multi-platform payouts",
      "Anomaly / fraud flagging",
    ],
    uiInspiration: ["Mercury", "Stripe", "Notion", "Cleo"],
    monetization: "Freemium subscription + paid tax export add-ons",
  },
  {
    id: "sample-3",
    projectName: "Synapse — Adaptive Learning Tutor",
    description:
      "A personalized AI tutor that builds dynamic lesson paths from any knowledge base and quizzes adaptively.",
    domain: "EdTech",
    targetUsers: "Self-learners, bootcamp students, university students",
    problemSolved: "Static courses don't adapt to each learner's gaps or pace.",
    whyPowerful:
      "RAG + adaptive assessment + learning analytics = a defensible, mission-driven product.",
    targetCompanies: ["Khan Academy", "OpenAI", "Anthropic", "Notion"],
    techStack: ["Next.js", "Supabase", "Gemini API", "LangChain", "Tailwind CSS"],
    aiIntegration: "Gemini for lesson generation, embeddings for knowledge retrieval, mastery model.",
    databasePlan: "Supabase: learners, modules, attempts, embeddings (pgvector).",
    frontendComplexity: 7,
    backendComplexity: 7,
    deploymentMethod: "Vercel + Supabase",
    scores: {
      resumeImpact: 8.6,
      githubValue: 8.8,
      recruiterImpression: 8.7,
      marketRelevance: 9.0,
      startupPotential: 8.8,
    },
    difficulty: "Advanced",
    estimatedBuildTime: "3-4 weeks",
    mvpFeatures: [
      "Upload a knowledge base / PDF",
      "Generate adaptive lesson path",
      "Quiz with instant feedback",
      "Mastery dashboard",
    ],
    advancedFeatures: [
      "Spaced-repetition scheduling",
      "Voice tutoring mode",
      "Cohort analytics for teachers",
    ],
    uiInspiration: ["Notion", "Perplexity", "Duolingo", "Linear"],
    monetization: "Freemium + school/team licenses",
  },
  {
    id: "sample-4",
    projectName: "Sentinel — AI Threat Intel Dashboard",
    description:
      "Aggregates CVEs, dark-web chatter, and your attack surface into prioritized, explainable risk scores.",
    domain: "Cybersecurity",
    targetUsers: "Security analysts, startup founders, blue teams",
    problemSolved: "Too many vulnerabilities, too little context on what actually matters.",
    whyPowerful:
      "Security + AI + data engineering is a rare, recruiter-magnet combination.",
    targetCompanies: ["CrowdStrike", "Cloudflare", "Microsoft", "Amazon"],
    techStack: ["Next.js", "PostgreSQL", "Python", "FastAPI", "Hugging Face"],
    aiIntegration: "NLP classification of threat feeds, embeddings for dedup, LLM risk explanations.",
    databasePlan: "Postgres (assets, findings, feeds) + time-series scoring history.",
    frontendComplexity: 7,
    backendComplexity: 8,
    deploymentMethod: "Vercel front + FastAPI on Render/Fly.io",
    scores: {
      resumeImpact: 9.2,
      githubValue: 8.9,
      recruiterImpression: 9.3,
      marketRelevance: 8.8,
      startupPotential: 8.5,
    },
    difficulty: "Industry Level",
    estimatedBuildTime: "4-6 weeks",
    mvpFeatures: [
      "Connect asset inventory",
      "Pull NVD CVE feed",
      "Explainable priority score",
      "Export remediation plan",
    ],
    advancedFeatures: [
      "Continuous attack-surface scanning",
      "Dark-web mention monitoring",
      "Slack alerting + Jira sync",
    ],
    uiInspiration: ["Linear", "Datadog", "CrowdStrike", "Vercel"],
    monetization: "Tiered SaaS by number of assets",
  },
  {
    id: "sample-5",
    projectName: "Forge — Vibe-Coding Prompt Marketplace",
    description:
      "A marketplace to craft, version, and share reusable AI coding prompts with live preview and ratings.",
    domain: "Developer Tools",
    targetUsers: "Indie hackers, AI engineers, power users of Cursor/Bolt",
    problemSolved: "Great AI coding prompts are scattered and unversioned.",
    whyPowerful:
      "Meta, product-led, developer-focused — strong GitHub and community signal.",
    targetCompanies: ["Vercel", "GitHub", "Replit", "Linear"],
    techStack: ["Next.js", "Supabase", "TypeScript", "Groq API", "Tailwind CSS"],
    aiIntegration: "Groq for prompt enhancement, embeddings for semantic prompt search.",
    databasePlan: "Supabase Postgres (prompts, versions, ratings) + RLS + full-text + vector.",
    frontendComplexity: 8,
    backendComplexity: 7,
    deploymentMethod: "Vercel + Supabase",
    scores: {
      resumeImpact: 8.7,
      githubValue: 9.4,
      recruiterImpression: 8.6,
      marketRelevance: 9.1,
      startupPotential: 9.0,
    },
    difficulty: "Advanced",
    estimatedBuildTime: "3-4 weeks",
    mvpFeatures: [
      "Create & version prompts",
      "Live AI-enhanced preview",
      "Search & filter marketplace",
      "Star / fork / copy",
    ],
    advancedFeatures: [
      "Prompt analytics & A/B testing",
      "Team workspaces",
      "Browser extension for Cursor/Bolt",
    ],
    uiInspiration: ["Raycast", "Linear", "Vercel", "GitHub"],
    monetization: "Free core + paid pro templates & teams",
  },
  {
    id: "sample-6",
    projectName: "Pulse — Realtime Audience Analytics for Creators",
    description:
      "Unifies YouTube, TikTok, and X analytics with AI insights and content-idea suggestions.",
    domain: "Creator Economy",
    targetUsers: "YouTubers, newsletter writers, social media managers",
    problemSolved: "Creators switch between 6 dashboards and still can't see what to make next.",
    whyPowerful:
      "Multi-platform data integration + recommendation engine = clear value + virality.",
    targetCompanies: ["Notion", "Stripe", "Perplexity", "Linear"],
    techStack: ["Next.js", "Supabase", "Gemini API", "PostgreSQL", "Vercel"],
    aiIntegration: "Gemini for content ideation & trend synthesis from multi-source metrics.",
    databasePlan: "Supabase Postgres (channels, metrics, insights) with scheduled sync jobs.",
    frontendComplexity: 8,
    backendComplexity: 7,
    deploymentMethod: "Vercel + Supabase + cron jobs",
    scores: {
      resumeImpact: 8.5,
      githubValue: 8.6,
      recruiterImpression: 8.8,
      marketRelevance: 9.3,
      startupPotential: 9.1,
    },
    difficulty: "Advanced",
    estimatedBuildTime: "3-4 weeks",
    mvpFeatures: [
      "Connect creator accounts",
      "Unified metrics dashboard",
      "AI weekly insight digest",
      "Content idea generator",
    ],
    advancedFeatures: [
      "Best-time-to-post predictions",
      "Competitor benchmarking",
      "Automated content calendar",
    ],
    uiInspiration: ["Linear", "Notion", "Stripe", "Perplexity"],
    monetization: "Freemium SaaS + creator agency plans",
  },
];
